CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/msr --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/dict_1 --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/msr --init_embedding=data/wordvec_100 > output/dict_hyper/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/as --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/dict_2 --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/as --init_embedding=data/wordvec_100 >> output/dict_hyper/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/cityu --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/dict_2 --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cityu --init_embedding=data/wordvec_100 >> output/dict_hyper/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/pku --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/dict_1 --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/pku --init_embedding=data/wordvec_100 >> output/dict_hyper/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/zx --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/zx_dict.txt --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/zx --init_embedding=data/wordvec_100 >> output/dict_hyper/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --train_batch_size=128 --data_dir=data/zx --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/zx_sougou_dict.txt --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/zx --init_embedding=data/wordvec_100 >> output/dict_hyper/test.log

echo "literature source dict" > output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/literature --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "literature domain dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/literature --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/literature_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "computer source dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/computer --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "computer domain dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/computer --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/computer_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "medicine source dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/medicine --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "medicine domain dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/medicine --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/medicine_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "finance source dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/finance --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log
echo "finance domain dict" >> output/dict_hyper/cross/test.log
CUDA_VISIBLE_DEVICES=5 python run_model.py --model=dict_hyper --do_train=false --do_eval=false --do_predict=true --early_stop=false --train_batch_size=128 --data_dir=data/cross/finance --vocab_file=data/vocab.txt --bigram_file=data/bigram.txt --dict_file=data/dict/source_dict,data/dict/finance_dict --config_file=config/dict_hyper.json --output_dir=output/dict_hyper/cross --init_embedding=data/wordvec_100 --learning_rate=0.01 --num_train_epochs=5.0 >> output/dict_hyper/cross/test.log